#!/bin/bash
sudo apt-get update
sudo apt-get upgrade -y
sudo apt install apache2 -y
sudo systemctl is-enabled apache2.service
sudo systemctl status apache2.service
sudo ufw allow 80/tcp comment 'accept Apache'
sudo ufw allow 443/tcp comment 'accept HTTPS connections'
sudo ufw status
curl -I http://localhost

